/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_zhps_hjctp_jni_NativeLoader */

#ifndef _Included_org_zhps_hjctp_jni_NativeLoader
#define _Included_org_zhps_hjctp_jni_NativeLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    createMdApi
 * Signature: (Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_createMdApi
  (JNIEnv *, jclass, jstring, jboolean, jboolean);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    registerMdSpi
 * Signature: (Lorg/zhps/hjctp/spi/MdSpi;)V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_registerMdSpi
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    registerMdFront
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_registerMdFront
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    registerMdLoginInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_registerMdLoginInfo
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    registerSubMarketData
 * Signature: ([Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_registerSubMarketData
  (JNIEnv *, jclass, jobjectArray, jint);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    connectMdServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_connectMdServer
  (JNIEnv *, jclass);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    getTradingTay
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zhps_hjctp_jni_NativeLoader_getTradingTay
  (JNIEnv *, jclass);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_stop
  (JNIEnv *, jclass);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    createTraderApi
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_createTraderApi
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    registerTraderSpi
 * Signature: (Lorg/zhps/hjctp/spi/TraderSpi;)V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_registerTraderSpi
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    registerTraderFront
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_registerTraderFront
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    registerTraderLoginInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_registerTraderLoginInfo
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    connectTraderServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_connectTraderServer
  (JNIEnv *, jclass);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    insertOrder
 * Signature: (Lorg/zhps/hjctp/entity/Iorder;)V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_insertOrder
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    killOrder
 * Signature: (Lorg/zhps/hjctp/entity/Korder;)V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_killOrder
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    queryOrder
 * Signature: (Lorg/zhps/hjctp/entity/Qorder;)V
 */
JNIEXPORT void JNICALL Java_org_zhps_hjctp_jni_NativeLoader_queryOrder
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    queryTradingAccount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zhps_hjctp_jni_NativeLoader_queryTradingAccount
  (JNIEnv *, jclass);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    queryInvestorPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zhps_hjctp_jni_NativeLoader_queryInvestorPosition
  (JNIEnv *, jclass);

/*
 * Class:     org_zhps_hjctp_jni_NativeLoader
 * Method:    queryInvestorPositionDetail
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zhps_hjctp_jni_NativeLoader_queryInvestorPositionDetail
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
