/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_hjctp_jni_NativeLoader */

#ifndef _Included_org_hjctp_jni_NativeLoader
#define _Included_org_hjctp_jni_NativeLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_hjctp_jni_NativeLoader
 * Method:    connect
 * Signature: (Ljava/lang/String;ZZLorg/hjctp/spi/MdSpi;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_hjctp_jni_NativeLoader_connect
  (JNIEnv *, jclass, jstring, jboolean, jboolean, jobject, jstring);

/*
 * Class:     org_hjctp_jni_NativeLoader
 * Method:    login
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_hjctp_jni_NativeLoader_login
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif

extern JavaVM *jvm;
extern jobject jjobj;
